### ISSUE TITLE
Handle PATCH, PUT, DELETE... and also `std` version

### ISSUE THREAD

**Issue by EwenQuim** [go-op/op#13]
Handle all methods.

See `mux.go`

**Comment by nhAnik** [comment]
HI @EwenQuim , can I work on this?

**Comment by EwenQuim** [comment]
I would like to let someone more "beginner" to work on this (as I could have fixed it quickly lol). 

Perhaps you could work on `Render` #3 ? I currently do not have a strategy for this issue, we have to look at other frameworks while trying to stick as much as possible to `net/http`

**Comment by nhAnik** [comment]
Sure. Please assign me.

**Comment by sidkhuntia** [comment]
Hi @EwenQuim  can i work on it ?

**Comment by EwenQuim** [comment]
Yes of course, go ahead !

**Comment by EwenQuim** [comment]
It would be nice to create a function `PostStd`, `PatchStd`, `DeleteStd` that look just like `GetStd` that already exists. 
These are the "standard library" version of the controllers

**Comment by EwenQuim** [comment]
Fixed by #14
